services:
  backend:
    build:
      context: ./backend
      target: prod
    env_file:
      - /home/debian/.services_datas/portalis/backend/.env
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./front_web
      target: runner
    environment:
    env_file:
      - /home/debian/.services_datas/portalis/front/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
